site_name: Evan's Notes
nav:
    - Home: index.md
    - UWAA557 - Physics of Fusion Plasmas:
      - Rules of thumb: ch10-0.md
      - Review:
        - Statistical Mechanics: ch10-1.md
        - Review of E&M: ch10-2.md
        - Lagrange Multipliers: ch10-3.md
      - Plasma Properties:
        - Wall-supported Plasma: ch11-1.md
        - Collisions: ch11-2.md
        - Oscillations: ch11-3.md
    - UWAA558 - Plasma Theory :
      - Introduction: ch12-1.md
      - Kinetic Models: ch12-2.md
      - Plasma Fluid Model: ch12-3.md
      - Two-Fluid Model: ch12-4.md
      - MHD: ch12-5.md
      - MHD Boundary Conditions: ch12-6.md
      - Fusion Equilibrium: ch12-7.md
      - Formulary: ch12-formulary.md
    - UWAA543 - Introduction to Compressible CFD:
      - Introduction:
        - Introduction: ch20-1.md
        - Governing Equations: ch20-2.md
        - Reduced Models: ch20-3.md
        - Equation Types: ch20-4.md
        - Panel Method: ch20-5.md
      - Finite Differencing:
        - Finite Difference Algorithms: ch21-1.md
        - Explicit Finite Difference Algorithms: ch21-2.md
        - Finite Difference and Finite Volume Methods: ch21-3.md
        - Implicit Algorithms: ch21-4.md
        - Numerical Boundary Conditions: ch21-5.md
        - Method of Lines: ch21-6.md
    - EPFLx - Plasma Physics Introduction:
      - Definition of Plasma: ch1-1.md
      - Particle motion in EM fields: ch1-2.md
    - Griffiths E&M:
      - Introduction: griffiths/index.md
      - 1 - Vector Analysis:
        - 1.1 - Vector Algebra: griffiths/ch1-1.md
        - 1.2 - Differential Calculus: griffiths/ch1-2.md
        - 1.3 - Integral Calculus: griffiths/ch1-3.md
        - 1.4 - Curvilinear Coordinates: griffiths/ch1-4.md
        - 1.5 - The Dirac Delta Function: griffiths/ch1-5.md
        - 1.6 - The Theory of Vector Fields: griffiths/ch1-6.md
      - 2 - Electrostatics:
        - 2.1 - The Electric Field: griffiths/ch2-1.md
        - 2.2 - Divergence and Curl of Electrostatic Fields: griffiths/ch2-2.md
        - 2.3 - Electric Potential: griffiths/ch2-3.md
        - 2.4 - Work and Energy in Electrostatics: griffiths/ch2-4.md
        - 2.5 - Conductors: griffiths/ch2-5.md
      - 3 - Potentials:
        - 3.1 - Laplace's Equation: griffiths/ch3-1.md
        - 3.2 - The Method of Images: griffiths/ch3-2.md
        - 3.3 - Separation of Variables: griffiths/ch3-3.md
        - 3.4 - Multipole Expansion: griffiths/ch3-4.md
        - Problems: griffiths/problems-ch3.md
      - 4 - Electric Fields in Matter:
        - 4.1 - Polarization: griffiths/ch4-1.md
        - 4.2 - The Field of a Polarized Object: griffiths/ch4-2.md
        - 4.3 - The Electric Displacement: griffiths/ch4-3.md
        - 4.4 - Linear Dielectrics: griffiths/ch4-4.md
      - 5 - Magnetostatics:
        - 5.1 - The Lorentz Force Law: griffiths/ch5-1.md
        - 5.2 - The Biot-Savart Law: griffiths/ch5-2.md
        - 5.3 - The Divergence and Curl of B: griffiths/ch5-3.md
        - 5.4 - Magnetic Vector Potential: griffiths/ch5-4.md
        - Problems: griffiths/problems-ch5.md
      - 6 - Magnetic Fields in Matter:
        - 6.1 - Magnetization: griffiths/ch6-1.md
        - 6.2 - The Field of a Magnetized Object: griffiths/ch6-2.md
        - 6.3 - The Auxiliary Field: griffiths/ch6-3.md
        - 6.4 - Linear and Nonlinear Media: griffiths/ch6-4.md
      - 7 - Electrodynamics:
        - 7.1 - Electromotive Force: griffiths/ch7-1.md
        - 7.2 - Electromagnetic Induction: griffiths/ch7-2.md
        - 7.3 - Maxwell's Equations: griffiths/ch7-3.md
        - Problems: griffiths/problems-ch7.md
      - 8 - Conservation Laws:
        - 8.0 - Phys544 Introduction: griffiths/ch8-0.md
        - 8.1 - Charge and Energy: griffiths/ch8-1.md
        - 8.2 - Momentum: griffiths/ch8-2.md
      - 9 - Electromagnetic Waves:
        - 9.1 - Waves in One Dimension: griffiths/ch9-1.md
        - 9.2 - Electromagnetic Waves in Vacuum: griffiths/ch9-2.md
        - 9.3 - Electromagnetic Waves in Matter: griffiths/ch9-3.md
        - 9.4 - Absorption and Dispersion: griffiths/ch9-4.md
        - 9.5 - Guided Waves: griffiths/ch9-5.md
        - Problems: griffiths/problems-ch9.md
      - 10 - Potentials and Fields:
        - 10.1 - The Potential Formulation: griffiths/ch10-1.md
        - 10.2 - Retarded Potentials: griffiths/ch10-2.md
        - 10.3 - Point Charges: griffiths/ch10-3.md
      - 11 - Radiation:
        - 11.1 - Dipole Radiation: griffiths/ch11-1.md
    - working: inprogress.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  font:
    # text: 'Noto Serif'
    # code: 'Roboto Mono'
    text: IBM Plex Sans
    code: IBM Plex Mono
  language: en
  features:
    - tabs
    - instant
  palette:
    primary: orange
    accent: light blue
  direction:
  favicon: assets/images/favicon.png
  icon:
    logo: material/book
  include_search_page: true
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: PeppyHare/pf-notes
repo_url: https://github.com/PeppyHare/pf-notes

extra_javascript:
  - extra.js

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css

markdown_extensions:
  - markdown_katex:
      no_inline_svg: False
      insert_fonts_css: True
      macro-file: macros.tex
  - admonition