site_name: My Docs
nav:
    - Home: index.md
    - 1 - The Plasma State:
      - 1.1 - Definition of Plasma: ch1-1.md
      - 1.2 - Particle motion in EM fields: ch1-2.md
    - Physics of Fusion Plasmas:
      - Rules of thumb: ch10-0.md
      - Review:
        - Statistical Mechanics: ch10-1.md
        - Review of E&M: ch10-2.md
        - Lagrange Multipliers: ch10-3.md
      - Plasma Properties:
        - Wall-supported Plasma: ch11-1.md
        - Collisions: ch11-2.md
        - Oscillations: ch11-3.md
    - Plasma Theory:
      - Introduction: ch12-1.md
      - Plasma Models: ch12-2.md
    - Introduction to Compressible CFD:
      - Introduction:
        - 20.1 - Introduction: ch20-1.md
        - 20.2 - Governing Equations: ch20-2.md
        - 20.3 - Reduced Models: ch20-3.md
        - 20.4 - Equation Types: ch20-4.md
        - 20.5 - Panel Method: ch20-5.md
      - Finite Differencing:
        - 21.1 - Finite Difference Algorithms: ch21-1.md
        - 21.2 - Explicit Finite Difference Algorithms: ch21-2.md
        - 21.3 - Finite Difference and Finite Volume Methods: ch21-3.md
        - 21.4 - Implicit Algorithms: ch21-4.md
        - 21.5 - Numerical Boundary Conditions: ch21-5.md
        - 21.6 - Method of Lines: ch21-6.md
    - working: inprogress.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  font:
    # text: 'Noto Serif'
    # code: 'Roboto Mono'
    text: IBM Plex Sans
    code: IBM Plex Mono
  language: 'en'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'light blue'
  direction:
  favicon: assets/images/favicon.png
  logo:
    icon: "book"
  include_search_page: true
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: 'PeppyHare/pf-notes'
repo_url: 'https://github.com/PeppyHare/pf-notes'


# This lets us render MathJax, the coolest thing since sliced bread!
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  - extra.js
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css
markdown_extensions:
  - mdx_math
  - admonition