site_name: Evan's Notes
nav:
    - Home: index.md
    - UWAA557 - Physics of Fusion Plasmas:
      - Rules of thumb: ch10-0.md
      - Review:
        - Statistical Mechanics: ch10-1.md
        - Review of E&M: ch10-2.md
        - Lagrange Multipliers: ch10-3.md
      - Plasma Properties:
        - Wall-supported Plasma: ch11-1.md
        - Collisions: ch11-2.md
        - Oscillations: ch11-3.md
    - UWAA558 - Plasma Theory :
      - Introduction: ch12-1.md
      - Kinetic Models: ch12-2.md
      - Plasma Fluid Model: ch12-3.md
      - Two-Fluid Model: ch12-4.md
      - MHD: ch12-5.md
      - MHD Boundary Conditions: ch12-6.md
      - Fusion Equilibrium: ch12-7.md
    - UWAA543 - Introduction to Compressible CFD:
      - Introduction:
        - Introduction: ch20-1.md
        - Governing Equations: ch20-2.md
        - Reduced Models: ch20-3.md
        - Equation Types: ch20-4.md
        - Panel Method: ch20-5.md
      - Finite Differencing:
        - Finite Difference Algorithms: ch21-1.md
        - Explicit Finite Difference Algorithms: ch21-2.md
        - Finite Difference and Finite Volume Methods: ch21-3.md
        - Implicit Algorithms: ch21-4.md
        - Numerical Boundary Conditions: ch21-5.md
        - Method of Lines: ch21-6.md
    - EPFLx - Plasma Physics Introduction:
      - Definition of Plasma: ch1-1.md
      - Particle motion in EM fields: ch1-2.md
    - working: inprogress.md

# Cool material theme: https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  font:
    # text: 'Noto Serif'
    # code: 'Roboto Mono'
    text: IBM Plex Sans
    code: IBM Plex Mono
  language: 'en'
  features:
    - tabs
    - instant
  palette:
    primary: 'indigo'
    accent: 'light blue'
  direction:
  favicon: assets/images/favicon.png
  icon:
    logo: "material/book"
  include_search_page: true
  search_index_only: true
  static_templates:
    - 404.html

extra:
  search:
    language: 'en'

repo_name: 'PeppyHare/pf-notes'
repo_url: 'https://github.com/PeppyHare/pf-notes'

extra_javascript:
  - extra.js

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css

markdown_extensions:
  - markdown_katex:
      no_inline_svg: False
      insert_fonts_css: True
      macro-file: macros.tex
  - admonition